# Generated by Django 2.2.4 on 2020-04-27 18:33

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=150, verbose_name='Доменное имя')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='uploads/logo', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты',
            },
        ),
    ]
