# Generated by Django 2.2.4 on 2020-04-29 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('blogengine', '0003_auto_20200411_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to='uploads/logo', verbose_name='Логотип')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name': 'Сайт Конф',
                'verbose_name_plural': 'Сайт Конф',
            },
        ),
    ]
